version: "3"

services:
  rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbit-nerdstore
  environment:
    RABBITMQ_DEFAULT_USER: "nerdstore"
    RABBITMQ_DEFAULT_PASS: "nerdstore"

  sql-server:
    image: luaan2012/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build: 
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"  

  web-mvc:
    image: luaan2012/nerdstore-web-mvc-ecommerce:latest
    build:
      context: ../src
      dockerfile: ./web/WebMVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - dpkeys:/var/data_protection_keys/
    ports:
      - "90:90"
      - "440:440"

  api-identidade:
    image: luaan2012/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./services/ES.Identidade.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5801;http://+5802

  api-carrinho:
    image: luaan2012/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    build:
      context: ../src
      dockerfile: ./services/ES.carrinho.API/Dockerfile
    restart: always             
    environment:      
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5601;http://+5602

  api-catalogo:
    image: luaan2012/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/ES.Catalogo.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5301;http://+5302

  api-cliente:
    image: luaan2012/nerdstore-api-cliente:latest
    container_name: nerdstore-api-cliente
    build:
      context: ../src
      dockerfile: ./services/ES.Cliente.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5201;http://+5202

  api-bff:
    image: luaan2012/nerdstore-api-bff:latest
    container_name: nerdstore-api-bff
    build:
      context: ../src
      dockerfile: ./api gateways/NS.BFF.Compras/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5401;http://+5402

  api-pagamentos:
    image: luaan2012/nerdstore-api-pagamento:latest
    container_name: nerdstore-api-pagamento
    build:
      context: ../src
      dockerfile: ./services/NS.pagamentos.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5501;http://+5502

  api-pedido:
    image: luaan2012/nerdstore-api-pedido:latest
    container_name: nerdstore-api-pedido
    build:
      context: ../src
      dockerfile: ./services/ES.pedido.API/Dockerfile
    restart: always 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5701;http://+5702

  nerdstore-server:
    image: luaan2012/nerdstore-server:latest
    container_name: nerdstore-server    
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "90:90"
      - "440:440"
    depends_on:
      - web-mvc

volumes:
    dpkeys: